- name: Add Microsoft Apt signing key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
- name: Add VS Code Repo
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    filename: vscode.list
- name: Install vscode
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - code

- name: Add Google Apt signing key
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
- name: Add Google Chrome Repo
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    filename: sources.list
- name: Install Google Chrome
  apt:
    name: google-chrome-stable

- name: Install Spotify
  shell: snap install spotify

- name: Install Intellij IDEA Ultimate
  shell: snap install intellij-idea-ultimate --classic

- name: Install Docker Prereqs
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - ca-certificates 
    - curl
    - software-properties-common
- name: Install Docker GPG Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
- name: Add Docker CE Repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
- name: Install Docker
  apt:
    name: docker-ce
- name: Add 'matt' To Docker Group
  user:
    name: matt
    groups: docker
    append: yes

- name: Install NodeJS
  shell: snap install node --classic --channel=10

- name: Install pip
  apt:
    name: python-pip
- name: psutil install
  pip:
    name: psutil

- name: GNOME Modification
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - gnome-tweak-tool
    - gnome-shell-extensions
    - git

- name: Clone Dash To Panel Repo
  git:
    repo: https://github.com/home-sweet-gnome/dash-to-panel.git
    dest: /tmp/dash-to-panel
- name: Build and Install Dash To Panel
  shell: make install
  args:
    chdir: /tmp/dash-to-panel


- name: Copy Ubuntu Logo For Apps Icon
  shell: cp cof_orange_hex.png ~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/img
- name: Read Access To Ubuntu Icon
  file:
    path: ~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/img/cof_orange_hex.png
    state: file
    mode: 0644 
- name: Enable Shell Extensions
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/enabled-extensions"
    value: "['user-theme@gnome-shell-extensions.gcampax.github.com', 'dash-to-panel@jderose9.github.com']"
- name: Use Ubuntu Logo For Apps Icon
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/show-apps-icon-file"
    value: "'/home/matt/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/img/cof_orange_hex.png'"
- name: No Favorite Apps
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/show-favorites"
    value: "false"
- name: Dash To Panel - Panel Size
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/panel-size"
    value: "40"
- name: Dash To Panel - App Icon Margin
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/appicon-margin"
    value: "1"
- name: Dash To Panel - App Icon Padding
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/appicon-padding"
    value: "4"
- name: Dash To Panel - Multi-monitor
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/multi-monitors"
    value: "true"
- name: Dash To Panel - Isolate Monitors
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/isolate-monitors"
    value: "true"
- name: Dash To Panel - Set Focus Highlight Opacity
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/focus-highlight-opacity"
    value: "20"
- name: Dash To Panel - Set Underbar Size
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/dot-size"
    value: "2"
- name: Dash To Panel - Hide Deskop Button
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/show-showdesktop-button"
    value: "false"
- name: Dash To Panel - No Window Preview Padding
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/window-preview-padding"
    value: "0"
- name: Dash to Panel - Tray Size
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/tray-size"
    value: "13"
- name: Dash to Panel - Tray Padding
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/tray-padding"
    value: "4"
- name: Dash to Panel - Status Icon Padding
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/status-icon-padding"
    value: "2"
- name: Dash to Panel - Window Preview Height
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/window-preview-height"
    value: "75"
- name: Dash to Panel - Window Preview Width
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/window-preview-width"
    value: "200"
- name: Dash to Panel - Window Preview Padding
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/window-preview-padding"
    value: "0"

- name: Interface Text
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/desktop/interface/font-name"
    value: "'Ubuntu 9'"
- name: Monospace Text
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/desktop/interface/monospace-font-name"
    value: "'Ubuntu Mono 10'"
- name: Legacy Window Titles Text
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/desktop/wm/preferences/titlebar-font"
    value: "'Ubuntu 9'"
- name: GTK Theme
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Yaru-dark'"
- name: Clock Show Date
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-date"
    value: "true"
- name: Clock AM/PM Format
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/desktop/interface/clock-format"
    value: "'12h'"
- name: Clock No Weekday
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-weekday"
    value: "false"

- name: Terminal Profile List
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/list"
    value: "['b1dcc9dd-5262-4d8d-a863-c897e6d979b9']"
- name: Terminal Profile Default
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/default"
    value: "'b1dcc9dd-5262-4d8d-a863-c897e6d979b9'"
- name: Terminal Profile Default Background Color
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-color"
    value: "'rgb(46,52,54)'"
- name: Terminal Profile Default Foreground Color
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/foreground-color"
    value: "'rgb(211,215,207)'"
- name: Terminal Profile Default Use Transparent Background
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-transparent-background"
    value: "true"
- name: Terminal Profile Default Transparency
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-transparency-percent"
    value: "7"
- name: Terminal Profile Default Don't Use Theme Colors
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-theme-colors"
    value: "false"
- name: Terminal Profile Default Don't Use Theme Transparency
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-theme-transparency"
    value: "false"

- name: Numlock On
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/settings-daemon/peripherals/keyboard/numlock-state"
    value: "'on'"

- name: Nautilus - List Folder View
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/nautilus/preferences/default-folder-viewer"
    value: "'list-view'"
- name: Nautilus - Small Zoom Level
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/nautilus/list-view/default-zoom-level"
    value: "'small'"
- name: Nautilus - Sidebar Width
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/nautilus/window-state/sidebar-width"
    value: "205"

- name: File Chooser - Show Hidden Files
  become: yes
  become_user: matt
  dconf:
    key: "/org/gtk/settings/file-chooser/show-hidden"
    value: "true"

- name: Media Keys - Set Home Super+e
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/home"
    value: "'<Super>e'"

- name: Set Git user.name
  git_config:
    name: user.name
    scope: global
    value: "Matt Butalla"
- name: Set Git user.email
  git_config:
    name: user.email
    scope: global
    value: "butallmj@gmail.com"