- name: Add Microsoft Apt signing key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
- name: Add VS Code Repo
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    filename: vscode.list
- name: Install vscode
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - code

- name: Add Google Apt signing key
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
- name: Add Google Chrome Repo
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    filename: sources.list
- name: Install Google Chrome
  apt:
    name: google-chrome-stable

- name: Install pip
  apt:
    name: python-pip
- name: psutil install
  pip:
    name: psutil
- name: gnome modification
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - gnome-tweak-tool
    - gnome-shell-extensions
    - gnome-themes-standard
    - gnome-shell-extension-dash-to-panel
    - arc-theme
- name: Papirus Repo
  apt_repository:
    repo: ppa:papirus/papirus
- name: Papirus Icon Theme
  apt:
    name: papirus-icon-theme
- name: Set Icon Theme
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'Papirus'"
- name: Enable Shell Extensions
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/enabled-extensions"
    value: "['user-theme@gnome-shell-extensions.gcampax.github.com', 'dash-to-panel@jderose9.github.com']"
- name: No Favorite Apps
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['']"
- name: Set Arc Theme
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Arc-Dark'"
- name: Set Arc Shell
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/user-theme/name"
    value: "'Arc-Dark'"
- name: Dash To Panel - Panel Size
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/panel-size"
    value: "40"
- name: Dash To Panel - App Icon Margin
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/appicon-margin"
    value: "0"