- name: Add Microsoft Apt signing key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
- name: Add VS Code Repo
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    filename: vscode.list
- name: Install vscode
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - code

- name: Add Google Apt signing key
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
- name: Add Google Chrome Repo
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    filename: sources.list
- name: Install Google Chrome
  apt:
    name: google-chrome-stable

- name: Install pip
  apt:
    name: python-pip
- name: psutil install
  pip:
    name: psutil

- name: GNOME Modification
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - gnome-tweak-tool
    - gnome-shell-extensions

- name: Clone Dash To Panel Repo
  git:
    repo: https://github.com/home-sweet-gnome/dash-to-panel.git
    dest: /tmp/dash-to-panel
- name: Build and Install Dash To Panel
  shell: make install
  args:
    chdir: /tmp/dash-to-panel

- name: Enable Shell Extensions
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/enabled-extensions"
    value: "['user-theme@gnome-shell-extensions.gcampax.github.com', 'dash-to-panel@jderose9.github.com']"
- name: No Favorite Apps
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/show-favorites"
    value: "false"
- name: Dash To Panel - Panel Size
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/panel-size"
    value: "40"
- name: Dash To Panel - App Icon Margin
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/appicon-margin"
    value: "1"
- name: Dash To Panel - App Icon Padding
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/appicon-padding"
    value: "4"
- name: Dash To Panel - Multi-monitor
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/multi-monitors"
    value: "true"
- name: Dash To Panel - Isolate Monitors
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/isolate-monitors"
    value: "true"
- name: Dash To Panel - Set Focus Highlight Opacity
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/focus-highlight-opacity"
    value: "20"
- name: Dash To Panel - Set Underbar Size
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/dot-size"
    value: "2"
- name: Dash To Panel - Hide Deskop Button
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/show-showdesktop-button"
    value: "false"
- name: GNOME Scaling
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/desktop/interface/text-scaling-factor"
    value: "0.9"
- name: GTK Theme
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Yaru-dark'"
- name: Terminal Profile List
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/list"
    value: "['b1dcc9dd-5262-4d8d-a863-c897e6d979b9']"
- name: Terminal Profile Default
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/default"
    value: "'b1dcc9dd-5262-4d8d-a863-c897e6d979b9'"
- name: Terminal Profile Default Background Color
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-color"
    value: "'rgb(46,52,54)'"
- name: Terminal Profile Default Foreground Color
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/foreground-color"
    value: "'rgb(211,215,207)'"
- name: Terminal Profile Default Use Transparent Background
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-transparent-background"
    value: "true"
- name: Terminal Profile Default Transparency
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-transparency-percent"
    value: "7"
- name: Terminal Profile Default Don't Use Theme Colors
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-theme-colors"
    value: "false"
- name: Terminal Profile Default Don't Use Theme Transparency
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-theme-transparency"
    value: "false"