- name: Add Microsoft Apt signing key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
- name: Add VS Code Repo
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    filename: vscode.list
- name: Install vscode
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - code
- name: Install pip
  apt:
    name: python-pip
- name: psutil install
  pip:
    name: psutil
- name: gnome modification
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - gnome-tweak-tool
    - gnome-shell-extensions
    - gnome-themes-standard
- name: Papirus Repo
  apt_repository:
    repo: ppa:papirus/papirus
- name: Papirus Icon Theme
  apt:
    name: papirus-icon-theme
- name: Set Icon Theme
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'Papirus'"
- name: Enable Shell Extensions
  become: yes
  become_user: matt
  dconf:
    key: "/org/gnome/shell/enabled-extensions"
    value: "['user-theme@gnome-shell-extensions.gcampax.github.com']"